[build]
  command = "npm run build"
  publish = ".next" # Set the publish directory to the directory where Next.js builds its output

[dev]
  command = "npm run start"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/predict/*"
  to = "/predict/:splat"
  status = 200
  force = true
